/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import Controller.MainController;
import Controller.TableInfo;
import Model.Users.User;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author dam2
 */
public class MainFrame extends javax.swing.JFrame {

    private JPanel cardo;
    private MainController mc;
    private CardLayout card;
    private MainPanel mP;
    private Game game;
    private Stats stats;
    private Menu menu;
    private User user;
    private NewGame ng;

    /**
     * Creates new form MainFrame
     * @param mc
     */
    public MainFrame(MainController mc) {
        initComponents();

        this.mc = mc;
        
        cardo = (JPanel) this.getContentPane();
        card = (CardLayout) cardo.getLayout();
        this.mP = new MainPanel(this); 
        this.menu = new Menu(this);
        cardo.add(mP, "MainPanel");
        cardo.add(menu, "Menu");
        makeFrameFullSize(this);
        
        showMainPanel();
    }

    private void makeFrameFullSize(JFrame aFrame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        aFrame.setSize(screenSize.width, screenSize.height);
    }
    

    public void showMainPanel(){
        this.user = null;
        card.show(cardo, "MainPanel");    
    }
    public void showStats(){
        this.stats = new Stats(this,new TableInfo(mc));
        cardo.add(stats, "Stats");
        card.show(cardo, "Stats");
    }
    public void showMenu(String user){
        this.user = mc.getUser(user);
        menu.setUser(user);
        card.show(cardo, "Menu");
    }
    public void showGame(List<User> enemies){
        this.game = new Game(user, enemies, this);
//        mc.startControllerModel(user, this.game);
        cardo.add(game, "Game");
        card.show(cardo,"Game");
    
    }
    public void showNewGame(){
        this.ng = new NewGame(mc.getEnemies(user), this);
        cardo.add(ng, "NewGame");
        card.show(cardo, "NewGame");
    }

    public MainController getMc() {
        return mc;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
