/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author dam2
 */
public class MainPanel extends javax.swing.JPanel {

    private JFrame mainFrame;

    /**
     * Creates new form MainPanel
     */
    public MainPanel(JFrame mF) {
        initComponents();
        this.mainFrame = mF;

        ImageIcon icon = new ImageIcon("DamOfEmpires\\Resources\\images\\background1.jpg");
        JLabel thumb = new JLabel();
        thumb.setIcon(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
