/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import Controller.MainController;
import Model.Terrain.Map;
import Model.Users.User;
import View.InfoGame;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import no.geosoft.cc.graphics.GScene;

/**
 *
 * @author dam2
 */
public class MainFrame extends javax.swing.JFrame {

    private JPanel cardo;
    private MainController mc;
    private CardLayout card;
    private MainPanel mP;
    private Game game;
    private Stats stats;
    private Menu menu;

    /**
     * Creates new form MainFrame
     * @param mc
     */
    public MainFrame(MainController mc) {
        initComponents();

        this.mc = mc;
        
        cardo = (JPanel) this.getContentPane();
        card = (CardLayout) cardo.getLayout();
        
        this.mP = new MainPanel(this);        
        this.stats = new Stats();
        this.menu = new Menu();
        
        cardo.add(mP, "MainPanel");
        cardo.add(stats, "Stats");
        cardo.add(menu, "Menu");
        makeFrameFullSize(this);
        
        showMainPanel();
    }

    private void makeFrameFullSize(JFrame aFrame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        aFrame.setSize(screenSize.width, screenSize.height);
    }
    
    public void createGame(User player, List<User> rivals){
        this.game = new Game(player, rivals);
        cardo.add(game, "Game");
    }
    public void showMainPanel(){
        card.show(cardo, "MainPanel");    
    }
    public void showStats(){
        card.show(cardo, "Stats");
    }
    public void showMenu(){
        card.show(cardo, "Menu");
    }    
    public void showGame(){
        card.show(cardo,"Game");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
