/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

/**
 *
 * @author dam2
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    
    private String user;
    private final MainFrame mf;
    
            
    public Menu(MainFrame mf) {
        initComponents();
        this.mf = mf;
        
        User.setText(user);
    }

    
    public void setUser(String user) {
        this.user = user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Play = new javax.swing.JButton();
        Stats = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        User = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        Diplomacy = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(Play, gridBagConstraints);

        Stats.setText("Stats and User Options");
        Stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(Stats, gridBagConstraints);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        add(Exit, gridBagConstraints);

        User.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        User.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(User, gridBagConstraints);

        LogOut.setText("LogOut");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(LogOut, gridBagConstraints);

        Diplomacy.setText("Diplomacy");
        Diplomacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiplomacyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(Diplomacy, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        // TODO add your handling code here:
        
        mf.showNewGame();
    }//GEN-LAST:event_PlayActionPerformed

    private void StatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatsActionPerformed
        // TODO add your handling code here:
        
        mf.showStats();
        
    }//GEN-LAST:event_StatsActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        mf.showMainPanel();
    }//GEN-LAST:event_LogOutActionPerformed

    private void DiplomacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiplomacyActionPerformed
        // TODO add your handling code here:
        mf.showDiplomacy();
        
    }//GEN-LAST:event_DiplomacyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Diplomacy;
    private javax.swing.JButton Exit;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton Play;
    private javax.swing.JButton Stats;
    private javax.swing.JLabel User;
    // End of variables declaration//GEN-END:variables
}
