/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import Controller.TableEnemies;
import Model.Users.User;
import java.util.List;

/**
 *
 * @author dam2
 */
public class NewGame extends javax.swing.JPanel {

    private List<User> enemies;
    private MainFrame mf;
    private TableEnemies te;
    /**
     * Creates new form NewGame
     */
    public NewGame(MainFrame mf, TableEnemies te) {
        initComponents();
        
        this.enemies = enemies;
        this.mf = mf;
        this.te = te;
        InnerTable.setModel(te);
        this.mf.showGame(enemies);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        table = new javax.swing.JScrollPane();
        InnerTable = new javax.swing.JTable();
        Enviar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        InnerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setViewportView(InnerTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(table, gridBagConstraints);

        Enviar.setText("Enviar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(Enviar, gridBagConstraints);

        jComboBox1.setMaximumRowCount(4);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JTable InnerTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane table;
    // End of variables declaration//GEN-END:variables
}
