/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import Model.Users.User;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author dam2
 */
public class Stats extends javax.swing.JPanel {

    private MainFrame mf;
    private User user;

    /**
     * Creates new form Stats
     */
    public Stats(MainFrame mf, TableModel tModel) {
        initComponents();
        this.mf = mf;
        this.user = mf.getUser();
        TableInfo.setModel(tModel);
        GameText.setText(String.valueOf(user.getPlays()));
        WinText.setText(String.valueOf(user.getWinRatio()));
        TimeText.setText(String.valueOf(mf.getMc().getDuration(user.getName())));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        InfoUser = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        PasswordText = new javax.swing.JTextField();
        Change = new javax.swing.JButton();
        Games = new javax.swing.JLabel();
        Win = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        GameText = new javax.swing.JLabel();
        WinText = new javax.swing.JLabel();
        TimeText = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Clasification = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableInfo = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        InfoUser.setLayout(new java.awt.GridBagLayout());

        Username.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 25, 0, 0);
        InfoUser.add(Username, gridBagConstraints);

        UsernameText.setPreferredSize(new java.awt.Dimension(70, 24));
        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 0);
        InfoUser.add(UsernameText, gridBagConstraints);

        Email.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 0, 0);
        InfoUser.add(Email, gridBagConstraints);

        EmailText.setPreferredSize(new java.awt.Dimension(70, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        InfoUser.add(EmailText, gridBagConstraints);

        Password.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 26, 0, 0);
        InfoUser.add(Password, gridBagConstraints);

        PasswordText.setPreferredSize(new java.awt.Dimension(70, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        InfoUser.add(PasswordText, gridBagConstraints);

        Change.setText("Change");
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 48, 6, 0);
        InfoUser.add(Change, gridBagConstraints);

        Games.setText("Games");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 22, 0, 0);
        InfoUser.add(Games, gridBagConstraints);

        Win.setText("Win Ratio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 22, 0, 0);
        InfoUser.add(Win, gridBagConstraints);

        Time.setText("Time Played");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 22, 0, 0);
        InfoUser.add(Time, gridBagConstraints);

        GameText.setText("jLabel7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 34, 0, 29);
        InfoUser.add(GameText, gridBagConstraints);

        WinText.setText("jLabel8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 34, 0, 29);
        InfoUser.add(WinText, gridBagConstraints);

        TimeText.setText("jLabel9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 34, 0, 29);
        InfoUser.add(TimeText, gridBagConstraints);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 6, 0);
        InfoUser.add(Back, gridBagConstraints);

        add(InfoUser);

        TableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableInfo);

        javax.swing.GroupLayout ClasificationLayout = new javax.swing.GroupLayout(Clasification);
        Clasification.setLayout(ClasificationLayout);
        ClasificationLayout.setHorizontalGroup(
            ClasificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClasificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        ClasificationLayout.setVerticalGroup(
            ClasificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClasificationLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(Clasification);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextActionPerformed

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed

        String name = UsernameText.getText();
        if (!name.isEmpty()) {
            if (mf.getMc().setUserName(name, user.getName())) {
                UsernameText.setText("Éxito");
            } else UsernameText.setText("Fallo");
        }
        String email = EmailText.getText();
        if (!email.isEmpty()) {
            if (mf.getMc().setEmail(email, user.getName())) {
                EmailText.setText("Éxito");
            } else EmailText.setText("Fallo");
        }

        String pass = PasswordText.getText();
        if (!pass.isEmpty()) {
            String auxPassword = JOptionPane.showInputDialog(this, "Introduce tu contraseña actual:", "Modificar Contraseña", JOptionPane.ERROR_MESSAGE);
            if (mf.getMc().logIn(user.getName(), auxPassword)) {
                if (mf.getMc().setPassword(pass, user.getName())) {
                    PasswordText.setText("Éxito");
                }else PasswordText.setText("Fallo");
            } else PasswordText.setText("Fallo");
        }
    }//GEN-LAST:event_ChangeActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        mf.showMenu(mf.getUser().getName());
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Change;
    private javax.swing.JPanel Clasification;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel GameText;
    private javax.swing.JLabel Games;
    private javax.swing.JPanel InfoUser;
    private javax.swing.JLabel Password;
    private javax.swing.JTextField PasswordText;
    private javax.swing.JTable TableInfo;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel TimeText;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JLabel Win;
    private javax.swing.JLabel WinText;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
